const busData = [
    {
        id: "01",
        name: "Bến Thành - Bến xe buýt Chợ Lớn",
        price: "10,000 VNĐ", time: "05:00 - 20:15", distance: "8 km", interval: "35 phút",
        outbound: ["Công Trường Mê Linh", "Bến Bạch Đằng", "Cục Hải Quan Thành Phố", "Chợ Cũ", "Trường Cao Thắng", "Trạm Trung chuyển trên đường Hàm Nghi", "Trường Ernst Thalmann", "KTX Trần Hưng Đạo", "Rạp Hưng Đạo", "Bệnh viện Răng Hàm Mặt", "Trần Đình Xu", "Tổng Cty Samco", "Chợ Nanci", "Nguyễn Biểu", "Trường Cao đẳng Kinh tế Đối ngoại", "Trần Bình Trọng", "Bệnh viện Chấn thương Chỉnh hình", "Rạp Đồng Tháp", "Rạp Đống Đa", "Đồng Khánh", "Nhà Văn hóa Quận 5", "Ngô Quyền", "Tản Đà", "Triệu Quang Phục", "Bưu điện Quận 5", "Hải Thượng Lãn Ông", "Chợ Kim Biên", "Bến xe buýt Chợ Lớn"],
        inbound: ["Bến xe buýt Chợ Lớn", "Tháp Mười", "Chợ Kim Biên", "Bưu điện Quận 5", "Rạp Đại Quang", "Lương Nhữ Học", "Triệu Quang Phục", "Đại học Sư phạm Thể dục thể thao", "Siêu thị Điện máy Chợ Lớn", "Ngô Quyền", "Chung cư Nguyễn Trãi", "Bệnh viện Nguyễn Tri Phương", "Trần Phú", "Bệnh viện Nguyễn Trãi", "Bệnh viện Chấn Thương Chỉnh hình", "Trần Bình Trọng", "Nguyễn Biểu", "Chợ Nanci", "Tổng Cty Samco", "Sở PCCC", "Hồ Hảo Hớn", "Bệnh Viện Răng Hàm Mặt", "Rạp Trần Hưng Đạo", "KTX Trần Hưng Đạo", "Nguyễn Kim", "Trạm Trung chuyển trên đường Hàm Nghi", "Nam Kỳ Khởi Nghĩa", "Chợ Cũ", "Giao lộ Hàm Nghi - Tôn Thất Đạm", "Hồ Tùng Mậu", "Bến Bạch Đằng", "Công Trường Mê Linh"]
    },
    {
        id: "39",
        name: "Bến Thành - Võ Văn Kiệt - Bến xe Miền Tây",
        price: "12,000 VNĐ", time: "05:00 - 22:00", distance: "17 km", interval: "55 phút",
        outbound: ["Bến xe buýt Sài Gòn", "Tôn Thất Tùng", "Nguyễn Thị Nghĩa", "Trường Emst Thalmann", "Trạm Trung chuyển trên đường Hàm Nghi", "Bảo tàng Mỹ Thuật", "Chợ Dân Sinh", "Chợ Nga", "Trường tiểu học Chương Dương", "Nhà Đèn Chợ Quán", "Trần Bình Trọng", "Bệnh viện Nhiệt Đới", "Chợ Hòa Bình", "Đại Thế Giới", "Hải Thượng Lãn Ông", "Chợ Kim Biên", "Cây xăng", "Bãi Sậy", "Mai Xuân Thưởng", "Bình Tiên", "Cầu Lò Gốm", "Cầu Rạch Cây", "Carina Plaza", "Đường số 1B", "Hồ Học Lãm", "Chùa Sùng Quang", "Chợ Khu phố 2", "Hàng Dương", "Ủy ban", "Lâm Thành", "Tên Lửa", "Bệnh viện Triều An", "Bến xe Miền Tây"],
        inbound: ["Bến xe Miền Tây", "Bệnh viện Triều An", "Hàng Dương", "SinCo", "Hoa hồng", "Chợ Khu phố 2", "Chùa Sùng Quang", "Trường Phú Định", "An Dương Vương", "Carina Plaza", "Cầu Rạch Cây", "Cầu Lò Gốm", "Bình Tiên", "Phạm Phú Thứ", "Bãi Sậy", "Tháp Mười", "Chợ Kim Biên", "Hải Thượng Lãn Ông", "Cầu Nguyễn Tri Phương", "An Bình", "Bệnh viện Nhiệt Đới", "Nhà đèn Chợ Quán", "Cầu Nguyễn Văn Cừ", "Hồ Hảo Hớn", "Chợ Nga", "Trường Cao Thắng", "Trạm Trung chuyển trên đường Hàm Nghi", "Khách sạn New World", "Nguyễn Thị Nghĩa", "Tôn Thất Tùng", "Bến xe buýt Sài Gòn"]
    },
    {
        id: "02",
        name: "Bác Cổ - Bến xe Yên Nghĩa",
        price: "10,000 VNĐ", time: "05:00 - 22:30", distance: "21 km", interval: "5 - 10 - 15 phút",
        outbound: ["(A) Bác Cổ", "Trạm trung chuyển xe buýt Trần Khánh Dư", "Đối diện Bệnh Viện Trung ương Quân đội 108", "Cổng làng văn hoá Mỹ Á", "Hè cạnh vườn hoa 19-8", "Trung tâm thương mại Tràng Tiền Plaza", "Bệnh viện Hữu Nghị Việt Nam - Cu Ba", "6-8 Tràng Thi", "Bệnh viện Việt Đức", "Cửa Nam", "Vườn hoa Lênin", "Văn Miếu Quốc Tử Giám", "Nhà Thờ Hàng Bột", "Ngã 5 Ô Chợ Dừa", "Bệnh viện Đa khoa Đống Đa", "Gò Đống Đa", "Đối diện Đại học Thủy Lợi", "Số 108 Nguyễn Trãi", "Ga Thượng Đình", "Đại học Khoa học - Tự nhiên", "Cục Sở hữu trí tuệ", "Bách hóa Thanh Xuân", "Đại Học Hà Nội", "Công ty CP Công trình GT", "Học viện An Ninh nhân dân", "Học viện Bưu chính viễn thông", "Big C Hà Đông - Hồ Gươm Plaza", "Sở Tư pháp Hà Nội - Cầu Trắng Hà Đông", "Bưu điện Hà Đông", "80 Quang Trung", "Nhà thi đấu Hà Đông", "Ga La Khê - Chợ La Khê", "Giữa số 428 - 430 Quang Trung", "530 - 532 Quang Trung", "678 - 680 Quang Trung", "Nissan Hà Đông", "Đối diện Trường TH Kinh tế Hà Tây", "(B) BX Yên Nghĩa"],
        inbound: ["(B) BX Yên Nghĩa", "Trường trung cấp Kinh tế", "Đối diện Nissan Hà Đông", "807 Quang Trung", "707-709 Quang Trung", "Ga La Khê", "Chợ La Khê", "Công ty CPLH Thực Phẩm", "Bệnh viện Đa khoa Hà Đông", "Bưu điện Hà Đông", "Sở Tư Pháp Hà Nội", "Ga Văn Quán", "Siêu thị Nguyễn Kim", "Đại học Kiến trúc Hà Nội", "Học viện An Ninh nhân dân", "Ga Phùng Khoang", "Đại học Hà Nội", "Cục Cảnh Sát Môi Trường", "Học viện Khoa học Xã hội", "Công ty Giày Thượng Đình", "Trường Đại học Khoa học tự nhiên", "Ga Thượng Đình", "Trường THPT Huỳnh Thúc Kháng", "Trường Đại học Thuỷ Lợi", "Đại học Công Đoàn", "83 Nguyễn Lương Bằng", "283 Tôn Đức Thắng", "Đối diện Nhà thờ Hàng Bột", "Văn Miếu Quốc Tử Giám", "Trường Tiểu Học Lý thường Kiệt", "Cửa Nam - Số 7 Nguyễn Thái Học", "Tháp Hà Nội", "Bệnh viện Hữu Nghị Việt Nam - Cu Ba", "Tràng Tiền Plaza", "Nhà hát Lớn Hà Nội", "(A) Bác Cổ"]
    },
    {
        id: "E04",
        name: "KĐT Smart City - Vincom Long Biên",
        price: "12,000 VNĐ", time: "05:00 - 21:30", distance: "25 km", interval: "15 phút",
        outbound: ["Điểm đỗ xe buýt Smart City", "TTTM Vincom Mega mall Smart City", "Số 4 đường Tây Mỗ", "Đình Phú Thứ", "Cầu Triền - Tây Mỗ", "Ngã 3 Biển Sắt", "Số 357 Đại Mỗ", "Đối diện 190 Đại Mỗ", "Đối diện 80 Đại Mỗ", "Đối diện Trường THCS Đại Mỗ", "Ngã 3 Ngọc Trục - Ngọc Đại", "Số 51 Vạn Phúc", "Số 63 Vạn Phúc", "Gold Silk Vạn Phúc", "Nhà Văn Hóa Công Đoàn Hà Nội", "Sở Tư Pháp Hà Nội", "Ga Văn Quán", "Siêu thị Nguyễn Kim", "Đại học Kiến trúc Hà Nội", "Học viện An Ninh nhân dân", "Ga Phùng Khoang", "Đại học Hà Nội", "Cục Cảnh Sát Môi Trường", "Học viện Khoa học Xã hội", "Công ty Giày Thượng Đình", "Trường Đại học Khoa học tự nhiên", "Ga Thượng Đình", "Trường THPT Huỳnh Thúc Kháng", "Số 69A Nguyễn Trãi", "225 Trường Chinh", "Bảo Tàng PKKQ", "Số 107 Trường Chinh", "197 Đại La", "89 Đại La", "32 Minh Khai", "Số 212-214 Minh Khai", "308 Minh Khai", "386-388 Minh Khai", "Times City", "Đối diện Sân Golf Long Biên", "Đối diện Trường THCS Phúc Đồng", "Đối diện Trường VinSchool", "Khu biệt thự Anh Đào", "Tòa nhà Văn phòng Symphony", "Vincom Long Biên"],
        inbound: ["Vincom Long Biên", "Đối diện Tòa nhà Văn phòng Symphony", "Đối diện Khu biệt thự Anh Đào", "Trường VinSchool", "Trường Tiểu học Phúc Đồng", "Sân Golf Long Biên", "Đối diện Vinhomes Times City", "259 Minh Khai", "199 Minh Khai", "139 - 141 Minh Khai", "Số 5 Minh Khai", "66 Đại La", "128C Đại La", "86 Trường Chinh", "Đối diện Bảo tàng PKKQ", "Số 108 Nguyễn Trãi", "Ga Thượng Đình", "Đại học Khoa học - Tự nhiên", "Cục Sở hữu trí tuệ", "Bách hóa Thanh Xuân", "Đại Học Hà Nội", "Chợ Phùng Khoang", "Học viện An Ninh nhân dân", "Học viện Bưu chính viễn thông", "Ga Văn Quán", "Sở Tư pháp Hà Nội", "Số 2 Chu Văn An", "Cầu Cong - Vạn Phúc", "Chùa Vạn Phúc", "Số 170 - 172 Vạn Phúc", "Ngã 3 Ngọc Trục - Đại Mỗ", "Đối diện 167 Ngọc Đại", "Số 40 - 42 Liên Cơ", "Số 178 Đại Mỗ", "Số 270 Đại Mỗ", "Số 522 Đại Mỗ", "Số 63 Tây Mỗ", "Làng Phú Thứ", "Điểm đỗ xe buýt Smart City"]
    },
    {
        id: "19",
        name: "Bãi đỗ xe buýt Trần Khánh Dư - Học viện Chính sách và Phát triển",
        price: "12,000 VNĐ", time: "05:00 - 21:00", distance: "26 km", interval: "11 - 15 phút",
        outbound: ["(A) Trung chuyển Trần Khánh Dư", "Trạm trung chuyển Trần Khánh Dư", "Trung tâm kỹ thuật cao Viện 108", "Bệnh viện Hữu Nghị Việt Xô", "Cạnh ngõ 18 Nguyễn Khoái", "Hè trước số nhà 202 - 204 Nguyễn Khoái", "82 Vĩnh Tuy", "505 Minh Khai", "Imperia Garden 2", "259 Minh Khai", "199 Minh Khai", "143-145 Minh Khai", "Số 5 Minh Khai", "26 Đại La", "Tập thể A10 128C Đại La", "86 Trường Chinh", "184 Trường Chinh", "Platform 610 Trường Chinh", "Số 108 Nguyễn Trãi", "Chợ Thượng Đình", "ĐH Khoa học - Tự nhiên", "Cục Sở hữu trí tuệ", "Bách hóa Thanh Xuân", "216 Nguyễn Trãi", "Công ty CP Công trình GT", "Số 10 Trần Phú", "Học viện Bưu chính viễn thông", "Big C Hà Đông", "Ga Văn Quán", "ĐD Sở Tư pháp Hà Nội", "Số 2 Chu Văn An", "Cầu Cong - Vạn Phúc", "Chùa Vạn Phúc", "Số 170 - 172 Vạn Phúc", "Điểm xén hè ngã 4 Vạn Phúc", "ĐD Công viên thiên văn học", "ĐD Trường liên cấp VIS", "ĐD Siêu thị Aeon Mall Hà Đông", "Gần C7-22 khu C GELEXIMCO", "Gần trường Tiểu học Dương Nội", "Qua ngã tư La Dương", "Đối diện CV Thiên đường Bảo Sơn", "KĐT GELEXIMCO A", "Tòa nhà 18T1", "Doanh trại quân đội nhân dân 1", "Cổng số 2 VinHomes Thăng Long", "Học viện Chính sách 1"],
        inbound: ["Học viện Chính sách 1", "Đối diện Cổng số 2 VinHomes Thăng Long", "Doanh trại Quân đội nhân dân Việt Nam", "Đối diện tòa nhà 18T1", "Đối diện KĐT GELEXIMCO A", "CV Thiên đường Bảo Sơn", "Gần Ngã Tư La Dương", "Đối diện trường Tiểu học Dương Nội", "Đối diện C7-22 khu C GELEXIMCO", "Siêu thị Aeon Mall Hà Đông", "Trường liên cấp VIS", "Công viên thiên văn học", "Điểm xén hè gần đường vào KĐT Dương Nội", "Trước ngã 4 Vạn Phúc", "Số 51 Vạn Phúc", "Số 63 Vạn Phúc", "Trước tòa nhà GoldSilk", "Nhà Văn Hóa Công Đoàn Hà Nội", "Sở Tư Pháp Hà Nội", "Ga Văn Quán", "Siêu thị Nguyễn Kim", "Đại học Kiến trúc Hà Nội", "Học viện An Ninh ND", "Ga Phùng Khoang", "521A Nguyễn Trãi", "Tổng Công ty Sông Đà", "Học viện Khoa học Xã hội", "Công ty Giày Thượng Đình", "Nhà máy thuốc lá Thăng Long", "Ga Thượng Đình", "Trường THPT Huỳnh Thúc Kháng", "Sân Vận động Thượng Đình", "Số 69A Nguyễn Trãi", "225 Trường Chinh", "173B Trường Chinh", "Số 107 Trường Chinh", "197 Đại La", "32 Minh Khai", "308 Minh Khai", "Viện kinh tế và kỹ thuật dệt may", "27 Vĩnh Tuy", "Qua đường dẫn lên cầu Vĩnh Tuy", "285 Nguyễn Khoái", "Đối diện Sun Plaza", "Đối diện phòng chụp cắt lớp vi tính", "Đối diện Khoa A11 Viện 108", "Đối diện khu tập thể 15C Trần Khánh Dư", "(A) Trung chuyển Trần Khánh Dư"]
    },
    {
        id: "103A",
        name: "Bến xe Mỹ Đình - Hương Sơn",
        price: "20,000 VNĐ", time: "05:00 - 21:00", distance: "65 km", interval: "15 - 25 phút",
        outbound: ["(A) BX Mỹ Đình", "Trước Phạm Hùng-Đình Thôn", "Nhà CT5 KĐT Sông Đà", "Nhà CT5-D KĐT Mỹ Đình", "Bảo tàng Hà Nội", "Trung tâm Hội nghị Quốc Gia", "259 Minh Khai", "Đối diện chung cư HH2 Bắc Hà", "Đối diện Công viên Hồ Phùng Khoang", "Gần lối vào trường THPT Trung Văn", "Trước ngã 4 Trung Văn", "Trước nhà chờ Mỗ Lao", "Qua ngã 3 Thanh Bình", "UBND phường Mỗ Lao", "Nhà LK3C", "Học viện Bưu chính viễn thông", "Big C Hà Đông", "Ga Văn Quán", "Đối diện Trung tâm Văn hóa Tỉnh Hà Tây", "70 Phùng Hưng", "Học viện Quân Y", "Cổng thôn Yên Xá", "Đối diện Nhà CT2A Khu đô thị Xa La", "Tường rào khách sạn Mường Thanh", "Sau ngã tư Mậu Lương", "Gần cổng khu nhà ở Hưng Thịnh", "Đối diện KĐT Thanh Hà", "Trường THCS Newton", "Đối diện sân Golf Thanh Hà", "Qua cầu Khê Tang", "Lối vào Làng văn hóa thôn Hạ", "Đối diện Trại tạm giam Thanh Xuân", "Ngã tư cống Sông Ái", "Làng Đại Định", "Đối diện trường THPT Thanh Xuân", "Cạnh Cty Kona", "Đối diện Bưu Điện Bình Đà", "Đối diện Vigracega Từ Liêm", "Cửa hàng sửa chữa xe máy Xuân Bắc", "BV huyện Thanh Oai", "Trạm biến áp Thanh Oai", "Chợ Kim Bài", "Đối diện UBND huyện Thanh Oai", "Cây xăng 370 Kim Bài", "Thôn Tân Thư", "Thôn Đôn Thư", "Trung tâm GDTX Thanh Oai", "Đối diện cổng làng Vũ Lăng", "Đối diện cây xăng Phố Vác", "Đình làng Canh Hoạch", "Đối diện cổng làng Ngọc Đình", "Làng Tảo Dương", "Cầu Xà Kiều", "Nghĩa trang liệt sỹ xã Quảng Phú Cầu", "Cầu Lão", "Đình chùa làng Bặt Ngõ", "Cổng làng xóm Chùa", "UBND xã Liên Bạt", "Trường THCS Liên Bạt", "Cổng làng Lương Xá", "190 Lê Lợi", "27 Quang Trung", "Cầu Vân Đình", "Bệnh viện Vân Đình", "Đình Thái Đường", "Cây xăng Vạn Thái", "Cây xăng Thái Đường", "Đường vào làng Nội Xá", "Đầu đê Hòa Xá", "Trung tâm Viettel Mỹ Đức", "UBND huyện Mỹ Đức", "Nghĩa trang Huyện Mỹ Đức", "293 Đại Nghĩa", "THPT Mỹ Đức A", "Bệnh viện Đa khoa huyện Mỹ Đức", "Cây xăng Đại Hưng", "Đường vào làng Trinh Tiết", "Cổng làng Kim Bôi", "Đường vào xã Hùng Tiến", "Trạm Y Tế Xã Đốc Tín", "Trường THPT Mỹ Đức C", "Trạm bơm Bạch Tuyết", "Đồn Công An Hương Son", "Xóm 2 Thôn Hội Xá", "Nhà văn hóa thôn Hội Xá", "Điện Máy Xanh", "Nhà thờ Họ Vương", "(B) BX Hương Sơn"],
        inbound: ["(B) BX Hương Sơn", "Đền trình", "Điện Máy Xanh", "Đối diện nhà văn hóa thôn Hội Xá", "Đối diện Đồn Công an Hương Son", "Trạm bơm Bạch Tuyết", "Trường THPT Mỹ Đức C", "Trạm Y Tế Xã Đốc Tín", "Xã Hùng Tiến", "Cổng làng Kim Bôi", "Đường vào làng Trinh Tiết", "Cây xăng Đại Hưng", "Bệnh viện Đa khoa huyện Mỹ Đức", "Trường PTTH Mỹ Đức A", "275 Đại Nghĩa", "Công An Huyện Mỹ Đức", "UBND huyện Mỹ Đức", "Trung tâm Viettel Mỹ Đức", "Đầu đê Hòa Xá", "Đường vào làng Nội Xá", "Cây xăng Thái Đường", "Cây xăng Vạn Thái", "Cột mốc Km28 - Quốc Lộ 21B", "Bệnh viện Vân Đình", "Cầu Vân Đình", "308 -310 Thị trấn Vân Đình", "202 Lê Lợi", "Cổng làng Lương Xá", "Trường THCS Liên Bạt", "UBND xã Liên Bạt", "Cổng làng xóm Chùa", "Đình làng Bặt Ngõ", "Cầu Lão", "Ngã 3 Quán Tròn", "Thôn Xà Cầu", "Cổng làng Tảo Dương", "Làng Ngọc Đình", "Đình làng Canh Hoạch", "Bưu điện huyện Thanh Oai", "Cổng làng Vũ Lăng", "Cửa hàng xăng dầu Phương Trung", "Thôn Đôn Thư", "Thôn Tân Thư", "Trạm xăng 370 Kim Bài", "UBND huyện Thanh Oai", "Bưu điện Kim Bài", "Trạm biến áp Thanh Oai", "BV huyện Thanh Oai", "Cửa hàng sửa chữa xe máy Xuân Bắc", "Vigracega Từ Liêm", "Bưu Điện Bình Đà", "Trường THPT Thanh Oai B", "Trường THPT Thanh Xuân", "Làng Đại Định", "Ngã tư cống Sông Ái", "Trại tạm giam Thanh Xuân", "Làng văn hóa thôn hạ", "Cầu Khê Tang", "Sân Golf Thanh Hà", "Trường mầm non Newton", "Khu đô thị Thanh Hà", "Khu nhà ở Hưng Thịnh", "Ngã tư Mậu Lương", "Nhà CT4B Khu đô thị Xa La", "Nhà CT2B", "Chung cư viện bỏng", "Viện 103 - Phùng Hưng", "Công ty CP Xây lắp điện Hà Tây", "Trung tâm Văn hóa Thông tin", "Sở Tư Pháp Hà Nội", "Ga Văn Quán", "Siêu thị Nguyễn Kim", "Đại học Kiến trúc Hà Nội", "Nhà BT01 Bắc Hà", "UBND phường Mỗ Lao", "Cầu Mỗ Lao", "Nhà chờ BRT Mỗ Lao", "Ngã 4 Trung Văn", "Trường THPT Trung Văn", "Công viên Hồ Phùng Khoang", "Chung cư HH2 Bắc Hà", "289A Khuất Duy Tiến", "TT Hội nghị Quốc Gia", "Bảo tàng Hà Nội", "Tòa nhà Landmark 72", "Nhà CT5 - KĐT Sông Đà", "Phạm Hùng-Đình Thôn", "122 Thái Thịnh", "(A) BX Mỹ Đình"]
    },
    {
        id: "22B",
        name: "Bến xe Giáp Bát - Đô Nghĩa",
        price: "10,000 VNĐ", time: "05:00 - 21:00", distance: "16 km", interval: "12 - 15 - 20 phút",
        outbound: ["(A) BX Giáp Bát", "Đối diện Bến xe Giáp Bát", "Ga Giáp Bát", "Đối diện 1251 Giải Phóng", "Gần đường vào KĐT Đại Kim", "Đối diện đài tưởng niệm chủ tịch HCM", "Cầu Dậu - Khu đô thị Bắc Linh Đàm", "Khu đô thị Kim Văn - Kim Lũ", "Trường Đại học dân lập Thăng Long", "Ngã 3 Nguyễn Xiển - Hoàng Đạo Thành", "Tập thể cao su Sao vàng", "Viện Công nghệ thực phẩm Trung Ương", "Bách hóa Thanh Xuân", "Đại Học Hà Nội", "Công ty CP Công trình GT", "Học viện An Ninh nhân dân", "Học viện Bưu chính viễn thông", "Big C Hà Đông - Hồ Gươm Plaza", "Sở Tư pháp Hà Nội", "Số 2 Chu Văn An", "Cầu Cong - Vạn Phúc", "Chùa Vạn Phúc - Hà Đông", "Số 170 - 172 Vạn Phúc", "Điểm xén hè qua ngã 4 Vạn Phúc", "KĐT Dương Nội", "Nam Cường Building", "KĐT An Hưng", "Cầu La Khê", "Nghĩa trang La Khê", "Tòa nhà CT7F The Sparks Nam Cường", "Công ty cây xanh Việt Nam", "(B) KĐT Đô Nghĩa"],
        inbound: ["(B) KĐT Đô Nghĩa", "Đối diện công ty cây xanh Việt Nam", "Cổng The Sparks Nam Cường", "Đối diện nghĩa trang La Khê", "350 Tố Hữu", "Đối diện đường vào KĐT An Hưng", "Đối diện Nam Cường Building", "Đường vào KĐT Dương Nội", "Trước ngã 4 Vạn Phúc", "Số 51 Vạn Phúc - Tòa Nhà Landmark", "Số 63 Vạn Phúc - Siêu Thị Vinmart", "Nhà văn hóa Công đoàn Hà Nội", "Sở Tư Pháp Hà Nội", "Ga Văn Quán", "Siêu thị Nguyễn Kim", "Đại học Kiến trúc Hà Nội", "Học viện An Ninh nhân dân", "Ga Phùng Khoang", "Đại học Hà Nội", "Cục Cảnh Sát Môi Trường", "Học viện Khoa học Xã hội", "Viện Công nghệ thực phẩm TW", "Khu tập thể Cao su sao Vàng", "Ngã 3 Nghiêm Xuân Yêm", "Trường Đại Học Dân lập Thăng Long", "Chung cư Kim Văn - Kim Lũ", "Cầu Dậu - Khu đô thị Bắc Linh Đàm", "Ao sen Làng Đại Từ", "Đường vào KĐT Đại Kim", "Ngã 3 Giải Phóng - Linh Đàm", "(A) BX Giáp Bát"]
    }
];

let isLoginMode = true;

// Khởi chạy khi trang tải xong
window.onload = function() {
    initApp();
};